# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["vim", "go"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = ".cargo/bin/topgrade"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Cleanup temporary or old files
#cleanup = true

[git]
max_concurrency = 5
repos = [
    "~/Development/sys/themes/Vimix-cursors",
    "~/Development/sys/themes/vimix-gtk-themes",
    "~/Development/sys/themes/vimix-icon-theme",
    "~/Development/sys/themes/vimix-kde",
    "~/Development/sys/util/ff-userjs",
]

# Don't pull the predefined git repos
#predefined_repos = false

# Arguments to pass Git when pulling Repositories
#arguments = "--rebase --autostash"

[composer]
self_update = false

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Upgrade Firefox user.js" = "cd ~/Development/sys/util/ff-userjs && ~/Development/sys/util/ff-userjs/patch.sh"
"Upgrade Neovim" = "cd ~/.config/nvim && make update"
"Update Vimix GTK theme" = "cd ~/Development/sys/themes/vimix-gtk-themes && ~/Development/sys/themes/vimix-gtk-themes/install.sh -t beryl"
"Update Vimix cursors" = "cd ~/Development/sys/themes/Vimix-cursors && ~/Development/sys/themes/Vimix-cursors/install.sh"
"Update Vimix icon theme" = "cd ~/Development/sys/themes/vimix-icon-theme && ~/Development/sys/themes/vimix-icon-theme/install.sh Beryl"
"Update Vimix kvantum theme" = "cd ~/Development/sys/themes/vimix-kde && ~/Development/sys/themes/vimix-kde/install.sh -t beryl"

#[linux]
# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"
#trizen_arguments = "--devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"

# Causes Topgrade to rename itself during the run to allow package managers 
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop to Cargo
#self_rename = true
